### ISSUE TITLE
[Artemis Student] HTTP 424

### ISSUE THREAD

**Issue by Clemens-Dautermann** [kit-sdq/programming-lecture-eclipse-artemis#159] opened 2022-01-04 21:50 UTC
When using `viewController.getFeedbackExercise();` Artemis returns a HTTP 424. Has anyone ever seen that and knows how to solve this?

**Comment by dfuchss** [comment] 2022-01-07 21:53
Does it occur regularly?

**Comment by dfuchss** [comment] 2022-03-18 15:14
I'll close it for now, since I could not reproduce :) .. Feel free to reopen it.

**Closed by dfuchss** 2022-03-18 15:14 UTC
